All: NumCheck Wait Exec Sleep Write

NumCheck: NumCheck.c
	gcc -o NumCheck NumCheck.c
Wait: Wait.c
	gcc -o Wait Wait.c
Exec: Exec.c
	gcc -o Exec Exec.c
Sleep: Sleep.c
	gcc -o Sleep Sleep.c
Write: writeFile.c
	gcc -o Write writeFile.c
